spring.application.name=backend

server.port=8080

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/nexus_db
spring.datasource.username=postgres
spring.datasource.password=Rakesh28112006@
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=TXlWZXJ5U2VjcmV0S2V5Rm9yTmV4dXNCYWNrZW5kUHJvamVjdDIwMjZNeVZlcnlTZWNyZXRLZXkxMjM0NTY=
jwt.expiration=86400000

# ===============================
# Security Logging
# ===============================
logging.level.org.springframework.security=DEBUG